### ISSUE TITLE
SSWE "embedding-results.zip" link is down

### ISSUE THREAD

**Issue by PaulErpen** [sweta20/Detecting-Cyberbullying-Across-SMPs#4]
Hey there,

Some colleagues and I are doing a reproducibility study for this paper. Sadly the link called "Sentiment Specific word embeddings (SSWE)" in the README is down.
I searched around and can't seem to find a backup anywhere. The file should be called "embedding-results.zip".
It'd be awesome if somebody could provide a version of the embeddings.

Thanks a lot in advance :)

**Comment by sweta20** [comment]
The embeddings were generated by the authors of the paper, "[Learning Sentiment-Specific Word Embedding
for Twitter Sentiment Classification](https://aclanthology.org/P14-1146.pdf)".  It might be worth reaching out to them directly as we shared the link available from the authors of the paper which seems to be down now.
